services:
  emails:
    build: .
    container_name: psitest-emails
    command: fastapi run app --host 0.0.0.0 --port 80
    ports:
      - 8006:80
    networks:
      - mynetwork
    env_file: ".env"
networks:
  mynetwork:
    external: true
